### ISSUE TITLE
Problems with file access

### ISSUE THREAD

**Issue by fustbariclation** [jieter/fph-parser#1]
There seems to be a simple file opening error:

sh-3.2# ./sleeps.py SUM0001.FPH 
Traceback (most recent call last):
  File "./sleeps.py", line 9, in <module>
    from fph.parseFile import parseFile
  File "/Volumes/FPHCARE/FPHCARE/ICON/04466185/fph-parser-master/fph/parseFile.py", line 11, in <module>
    from flow import FlowFile
ImportError: No module named flow
sh-3.2# ./dumpcsv.py /Volumes/FPHCARE/FPHCARE/ICON/04466185/FLW0001.FPH 
Traceback (most recent call last):
  File "./dumpcsv.py", line 9, in <module>
    from fph.parseFile import parseFile
  File "/Volumes/FPHCARE/FPHCARE/ICON/04466185/fph-parser-master/fph/parseFile.py", line 11, in <module>
    from flow import FlowFile
ImportError: No module named flow
sh-3.2#

**Comment by jieter** [comment]
Hmm, seems I forgot to add fph/flow.py to the repo. Just pushed it.
